name: rohd
version: 0.6.6
description: The Rapid Open Hardware Development (ROHD) framework, a framework for describing and verifying hardware.
homepage: https://intel.github.io/rohd-website
repository: https://github.com/intel/rohd
issue_tracker: https://github.com/intel/rohd/issues
documentation: https://intel.github.io/rohd-website/docs/sample-example/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  logging: ^1.3.0
  meta: ^1.17.0
  test: ^1.26.3

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^6.0.0
  yaml: ^3.1.3
